const courseData = {
  "Web Development": [
    {
      title: "React for Beginners",
      description: "Build modern web apps using React.js",
      instructor: "John Doe",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$49",
      
    },
    {
      title: "Advanced Next.js",
      description: "SSR and SSG with Next.js",
      instructor: "Jane Smith",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$59",
      
    },
    {
      title: "Vue Masterclass",
      description: "Learn Vue.js from scratch",
      instructor: "Emma Brown",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$45",
     
    },
    {
      title: "Node.js Essentials",
      description: "Backend development with Node.js",
      instructor: "Mike Johnson",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$39",
      
    },
    {
       title: "Node.js Essentials",
       description: "Build dynamic apps with Angular",
       instructor: "Olivia Green",
       image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
       price: "$42",
        
    },
    {
      title: "Fullstack JavaScript",
      description: "MERN stack development",
      instructor: "Liam White",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$69",
     
    },
    {
      title: "CSS Grid & Flexbox",
      description: "Responsive layouts with CSS",
      instructor: "Sophia Hall",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$30",
    },
    {
      title: "TypeScript Deep Dive",
      description: "Strongly typed JavaScript",
      instructor: "James King",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "Progressive Web Apps",
      description: "Build offline-capable apps",
      instructor: "Mia Scott",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$50",
    },
    {
      title: "Web Performance Optimization",
      description: "Speed up your website",
      instructor: "Ethan Lewis",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
  ],

  "Data Science": [
    {
      title: "Python for Data Science",
      description: "Data analysis and visualization with Python",
      instructor: "Alice Williams",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$59",
    },
    {
      title: "Machine Learning A-Z",
      description: "Comprehensive ML course with projects",
      instructor: "Bob Martin",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$99",
    },
    {
      title: "Deep Learning with TensorFlow",
      description: "Neural networks and deep learning",
      instructor: "Cathy Lee",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$79",
    },
    {
      title: "Statistics for Data Science",
      description: "Fundamentals of statistics",
      instructor: "David Kim",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$49",
    },
    {
      title: "Data Visualization with Tableau",
      description: "Interactive visual analytics",
      instructor: "Ella Young",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "SQL for Data Analysis",
      description: "Master SQL queries",
      instructor: "Frank Adams",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$35",
    },
    {
      title: "Natural Language Processing",
      description: "Text analysis with NLP",
      instructor: "Grace White",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$65",
    },
    {
      title: "Big Data with Hadoop",
      description: "Handling large datasets",
      instructor: "Hank Clark",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$70",
    },
    {
      title: "Data Science Capstone Project",
      description: "Real-world data science project",
      instructor: "Isla Turner",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$85",
    },
    {
      title: "R Programming Basics",
      description: "Statistical computing with R",
      instructor: "Jack Wilson",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
  ],

  "Digital Marketing": [
    {
      title: "SEO Basics",
      description: "Improve website ranking",
      instructor: "Emily Davis",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$29",
    },
    {
      title: "Social Media Marketing",
      description: "Marketing strategies on social platforms",
      instructor: "Frank Harris",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$39",
    },
    {
      title: "Google Ads Mastery",
      description: "Effective Google Ads campaigns",
      instructor: "Grace Wilson",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$49",
    },
    {
      title: "Email Marketing",
      description: "Manage email campaigns",
      instructor: "Henry Clark",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$35",
    },
    {
      title: "Content Marketing Strategy",
      description: "Create compelling content",
      instructor: "Ivy Lee",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$45",
    },
    {
      title: "Affiliate Marketing Basics",
      description: "Earn through affiliate sales",
      instructor: "Jack Brown",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$30",
    },
    {
      title: "Instagram Marketing",
      description: "Grow audience on Instagram",
      instructor: "Kate Green",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
    {
      title: "YouTube Marketing",
      description: "Build brand with YouTube",
      instructor: "Leo Smith",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "Facebook Ads Mastery",
      description: "Targeted Facebook advertising",
      instructor: "Mia Thomas",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$50",
    },
    {
      title: "Google Analytics Fundamentals",
      description: "Track and analyze website data",
      instructor: "Nick Allen",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$35",
    },
  ],

  "Graphic Design": [
    {
      title: "Adobe Photoshop Basics",
      description: "Learn photo editing",
      instructor: "Ivy Martinez",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$45",
    },
    {
      title: "Illustrator for Beginners",
      description: "Vector graphics and logos",
      instructor: "Jack Thomas",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
    {
      title: "UI/UX Design Fundamentals",
      description: "Design user-friendly interfaces",
      instructor: "Karen Lewis",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$60",
    },
    {
      title: "Canva Design Essentials",
      description: "Create stunning graphics",
      instructor: "Leo Walker",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$25",
    },
    {
      title: "Logo Design Masterclass",
      description: "Create professional logos",
      instructor: "Mona Carter",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$50",
    },
    {
      title: "Adobe InDesign Basics",
      description: "Layout and publishing",
      instructor: "Nate Brooks",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
    {
      title: "3D Modeling with Blender",
      description: "Create 3D art and animations",
      instructor: "Olivia Price",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$70",
    },
    {
      title: "Typography Essentials",
      description: "Master fonts and styles",
      instructor: "Paul Reed",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$30",
    },
    {
      title: "Adobe XD UI Design",
      description: "Prototyping and wireframing",
      instructor: "Quinn Bell",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "Photography for Designers",
      description: "Improve your photography skills",
      instructor: "Rachel Fox",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$45",
    },
  ],

  Cybersecurity: [
    {
      title: "Ethical Hacking Basics",
      description: "Introduction to hacking techniques",
      instructor: "Sam Wilson",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$60",
    },
    {
      title: "Network Security Fundamentals",
      description: "Protect networks from attacks",
      instructor: "Tina Clark",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "Penetration Testing",
      description: "Advanced hacking simulations",
      instructor: "Uma Singh",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$75",
    },
    {
      title: "Cybersecurity for Beginners",
      description: "Basics of cybersecurity",
      instructor: "Victor Lee",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$45",
    },
    {
      title: "Cryptography Essentials",
      description: "Learn encryption and decryption",
      instructor: "Wendy Brooks",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$50",
    },
    {
      title: "Incident Response",
      description: "How to handle security breaches",
      instructor: "Xander Young",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$60",
    },
    {
      title: "Security Compliance",
      description: "Understand regulations and laws",
      instructor: "Yara Mitchell",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
    {
      title: "Cloud Security Basics",
      description: "Secure cloud environments",
      instructor: "Zane Carter",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "Malware Analysis",
      description: "Analyze and detect malware",
      instructor: "Ava Parker",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$70",
    },
    {
      title: "Firewall Management",
      description: "Configure and manage firewalls",
      instructor: "Ben Stewart",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$50",
    },
  ],

  "Artificial Intelligence": [
    {
      title: "AI Fundamentals",
      description: "Basics of artificial intelligence",
      instructor: "Clara Brooks",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "Neural Networks",
      description: "Deep learning basics",
      instructor: "Derek Hunt",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$70",
    },
    {
      title: "Reinforcement Learning",
      description: "AI learning through rewards",
      instructor: "Ella Reed",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$80",
    },
    {
      title: "Computer Vision",
      description: "Image recognition and processing",
      instructor: "Felix King",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$75",
    },
    {
      title: "Natural Language Processing",
      description: "Text and speech AI",
      instructor: "Grace Ford",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$65",
    },
    {
      title: "AI Ethics",
      description: "Ethical implications of AI",
      instructor: "Harry Wells",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
    {
      title: "AI in Healthcare",
      description: "Applications of AI in medicine",
      instructor: "Iris Carter",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$60",
    },
    {
      title: "Generative AI",
      description: "Create content using AI",
      instructor: "Jackie Moore",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$85",
    },
    {
      title: "AI Project Deployment",
      description: "Deploy AI models to production",
      instructor: "Kyle Adams",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$70",
    },
    {
      title: "Robotics with AI",
      description: "AI applications in robotics",
      instructor: "Lara Fox",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$75",
    },
  ],

  "Mobile App Development": [
    {
      title: "Android Development",
      description: "Build apps for Android",
      instructor: "Mark Taylor",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$50",
    },
    {
      title: "iOS Development with Swift",
      description: "Create apps for iPhone",
      instructor: "Nina Brooks",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$55",
    },
    {
      title: "Flutter for Beginners",
      description: "Cross-platform apps",
      instructor: "Oscar Green",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$60",
    },
    {
      title: "React Native Essentials",
      description: "Build mobile apps with React Native",
      instructor: "Paula Clark",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$58",
    },
    {
      title: "Mobile UI Design",
      description: "Design interfaces for apps",
      instructor: "Quinn Harris",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$45",
    },
    {
      title: "Kotlin for Android",
      description: "Modern Android programming",
      instructor: "Ryan Lee",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$52",
    },
    {
      title: "App Monetization",
      description: "Make money from your apps",
      instructor: "Sara Young",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$40",
    },
    {
      title: "Mobile Game Development",
      description: "Create games for mobile",
      instructor: "Tom Walker",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$65",
    },
    {
      title: "Push Notifications",
      description: "Engage users with notifications",
      instructor: "Uma King",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$35",
    },
    {
      title: "App Testing & Debugging",
      description: "Ensure quality apps",
      instructor: "Vince Allen",
      image: "https://dummyimage.com/400x300/cccccc/000000&text=Course+Image",
      price: "$50",
    },
  ],
};

export default courseData;
