name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >> ~/.ssh/config <<EOL
          Host vps
            HostName 77.37.44.8
            User root
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          EOL

      - name: Deploy and Build on VPS
        run: |
          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            TARGET_DIR="/var/www/peerprogrammers/developement/frontend_peerprogrammers"
          else
            TARGET_DIR="/var/www/peerprogrammers/production/frontend_peerprogrammers"
          fi

          ssh vps "
            set -e  # Exit if any command fails
            cd $TARGET_DIR

            echo 'Fetching latest code...'
            git fetch origin
            git reset --hard origin/${GITHUB_REF_NAME}

            echo 'Installing dependencies...'
            npm ci --legacy-peer-deps

            echo 'Building React app...'
            npm run build

            echo 'Restarting application...'
            # Restart app with PM2 (or start if not running)
            if pm2 list | grep -q 'frontend-app'; then
              pm2 restart frontend-app
            else
              pm2 start npm --name 'frontend-app' -- start
            fi

            echo 'Deployment completed successfully.'
          "
