name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >> ~/.ssh/config <<EOL
          Host vps
            HostName 77.37.44.8
            User root
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          EOL

      - name: Deploy and Build on VPS
        run: |
          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            TARGET_DIR="/var/www/peerprogrammers/developement/frontend_peerprogrammers"
          else
            TARGET_DIR="/var/www/peerprogrammers/production/frontend_peerprogrammers"
          fi

          ssh vps "
            set -e
            cd $TARGET_DIR

            echo 'Fetching latest code...'
            git fetch origin
            git reset --hard origin/${GITHUB_REF_NAME}

            echo 'Installing dependencies...'
            npm ci --legacy-peer-deps

            echo 'Building React app...'
            npm run build

            echo 'Deploying build files to Nginx directory...'
            # Adjust this path if your Nginx serves from a different folder
            rm -rf /var/www/html/*
            cp -r build/* /var/www/html/

            echo 'Deployment completed successfully.'
          "
